### ISSUE TITLE
Set up build failure notifications

### ISSUE THREAD

**Issue by davehunt** [mozilla/wpt-api#144]
We recently had some downtime that went unnoticed for a little over a day. It would be great to get IRC and email notifications on failures so we can respond faster in these situations. I would suggest fte-ci for the email and #perftest-alerts for IRC.

**Comment by stephendonner** [comment]
@davehunt 👍 , but I do wonder: (how/if?) we can scale up the number of sites tested, with these individual (per-site, currently) alert notifications?

**Comment by stephendonner** [comment]
Fixed by https://github.com/mozilla/wpt-api/commit/cb8ad0b0c5d522b0565608d9e51ee2ee5f453646
