### ISSUE TITLE
Switch medianMetric from loadTime to SpeedIndex

### ISSUE THREAD

**Issue by stephendonner** [mozilla/wpt-api#153]
@davehunt @philbooth @soulgalore

We're currently running with the default ```medianMetric``` of ```loadTime``` which is problematic and antiquated, as a measure, particularly for our primarily client-based use-cases/concerns.

The recommendation from the WebPageTest project itself is to replace this default with, instead, ```SpeedIndex```.  I believe this is also what Browsertime/Sitespeed, et al. use, and I know that SpeedCurve and Fasterize used it.

This will not change any of the gathered/stored/published metrics; it will, rather, change off of *which* metric we base our median run.

https://github.com/WPO-Foundation/webpagetest/issues/767#issuecomment-351850556

**Comment by soulgalore** [comment]
We use that as default for our runs at Wikimedia. There's one configuration in the API so that the right run is picked and then you also need to configure the settings file in the server (so the gui pick the right run):
```
; Selects the metric to use for the median run (defaults to loadTime)
medianMetric=SpeedIndex
```

**Comment by stephendonner** [comment]
Thanks as always, @soulgalore! I also took care of this from the command-line/API side, just now: https://github.com/mozilla/wpt-api/pull/184
