### ISSUE TITLE
Get 3 sites running periodically and publishing somewhere visible

### ISSUE THREAD

**Issue by karlht** [mozilla/wpt-api#56]
This is probably YouTube, Google, and one other.

Yan, this is the issue I was going to tag you on, but I can't find your Github ID.  Ah, it's @yor-mozilla-com.

**Comment by karlht** [comment]
Also, @stuartphilp may be interested in this.

**Comment by stephendonner** [comment]
So we're not also losing days/weeks' worth of test data, we now have the top 10 measuring and reporting in to DataDog (but only the top 3 *visualized* for now)

After we address some scaling issues (EC2 instance size + chart/graph creation/labeling/annotations, etc. ), we'll plot the remaining 7, and should be in a great place to start working towards 50 (and then probably 500?) Alexa Topsites tested.

Closing this out, as the original milestone has been met/exceeded 👍
