### ISSUE TITLE
Confer and agree on our (alexa-topsites branch) Mozilla Metrics Pipeline schema

### ISSUE THREAD

**Issue by stephendonner** [mozilla/wpt-api#92]
Before we can (should) publish our metrics to the Mozilla Metrics Pipline (https://github.com/mozilla/wpt-api/issues/91), we need to discuss, agree on, and then codify its schema, here:

https://github.com/mozilla-services/mozilla-pipeline-schemas

By the nature of these metrics, their scope(s), multiple use-cases for the individual + larger set of data, etc., it'll take a multi-team effort to get right.

Openly-viewable and commentable (by anyone with the link) Google Doc here: https://docs.google.com/document/d/1eypZsuiqb1kzxbDEzFuxRT6ZCZcAXvRWaz5icZa-qFY/edit#

**Comment by stephendonner** [comment]
Suggestion from @soulgalore is:

"I think you should have something like this:
```webpagetest.extra.site.page.view.connectivity.device.browser.channel.metricType.metric.type```

**Examples:**
```webpagetest.default.www_wikipedia.org._.firstView.cable.desktop.firefox.nightly.visualMetric.render.median```

But it also depends on how you wanna graph the metrics?
Like what’s the most common use case? Compare each site per browser? Maybe you wanna shuffle view/connectivity/device etc."

So, for our examples:

* **Desktop Firefox:**
```webpagetest.default.www_google.com._firstView.cable.desktop.firefox.nightly.visualMetric.firstPaint.median```
* **Mobile Firefox:**
```webpagetest.default.www_google.com._firstView.cable.mobile.firefox.nightly.visualMetric.firstPaint.median```

@soulgalore: can you say a little more about the taxonomy of the fieldnames for your [visualMetric] entry?  How do/would you categorize the metrics' grouping?  Thanks as always!

Keep commenting here + in the [Google Doc](https://docs.google.com/document/d/1eypZsuiqb1kzxbDEzFuxRT6ZCZcAXvRWaz5icZa-qFY/edit#), everyone; thanks!

@stuartphilp @vchin @digitarald @onkeltom @godelstheory @mreid-moz - just a reminder for us to consider and hopefully confer soonish (very likely given this work week!)

**Comment by soulgalore** [comment]
> can you say a little more about the taxonomy of the fieldnames for your [visualMetric] entry? How do/would you categorize the metrics' grouping? Thanks as always!

I think you wanna keep them separated per group, then it's easier when you make your dashboards instead of keeping them all on the same level:
* VisualMetrics=metric collected by analysing the video (start render, Speed Index, last visual change etc)
* Technical metrics = metrics reported by the browser, all the things from navigation timing api, time to first non blank etc
* Page metrics = metrics from the page, number of requests, sizes etc.

**Comment by godelstheory** [comment]
The granularity provided by `webpagetest.default.www_google.com._firstView.cable.desktop.firefox.nightly.visualMetric.firstPaint.median` will be very useful for the wide variety of potential comparisons/analyses we would like to perform. 

From the data science perspective, storing as much distinguishing data as possible increases the value of the data. Therefore, having a key for session state will be valuable. In regards, to huge architectural changes, the build IDs should hold that information. Though it is useful for dashboard visualization, it isn't necessary for downstream analyses.

Though it is verbose, it seems easier to manage a slew of keys, then try to post-process to enable visualization, etc...

**Comment by stephendonner** [comment]
We're in the submission (to Telemetry!) stage over in https://github.com/mozilla/wpt-api/pull/236 (after a merge of https://github.com/mozilla-services/mozilla-pipeline-schemas/pull/216 and then testing, reviews, more testing, etc.).

Closing, since this is well-covered and underway!
