### ISSUE TITLE
Wrong link to Datadog dashboard in README

### ISSUE THREAD

**Issue by stefounet** [mozilla/wpt-api#94]
In the README, links to DD dashboard don't work:
 - either in `master`: https://app.datadoghq.com/dash/827265/firefox-accounts-dev-first-run-page-perf-metrics?live=true
 - or in `alexa-topsites`: https://app.datadoghq.com/dash/879449

<img width="720" alt="image" src="https://user-images.githubusercontent.com/686317/47031556-67093880-d170-11e8-8141-eaa10a27f7cd.png">

May be they're restricted to Mozillian?

**Comment by stephendonner** [comment]
Hi, @stefounet - sorry, but the graphs in DataDog are Mozillian-only (with an additional account/permission setting, too).

We're working on nailing down the schema, and then we can start publishing to a Mozilla Metrics ingestion point, and hopefully have open, and openly visible, metrics!

Leaving this open to remind me to add additional information around that, in the README; thanks for noticing and reporting!

**Comment by stefounet** [comment]
Hi Stephen and thank you for the quick reply!

**Comment by stephendonner** [comment]
Thanks again, @stefounet, and apologies for the delay; please continue to file Issues and/or PRs; cheers!
